site_name: Binance Chain Docs
site_description: Binance Chain Technology Documentation
site_author: Binance Chain Community

repo_url: https://github.com/binance-chain/
edit_uri: ""
use_directory_urls: false

theme:
  name: 'material'
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: 'yellow'
    accent: 'grey'
  logo:
    icon: 'build'
  feature:
    tabs: true
extra_css:
       - stylesheets/dark_theme.css
       - stylesheets/codehilite.css
nav:
  - Home: index.md
  - API Reference:
    - HTTP API - Paths and Models: api-reference/dex-api/paths.md
    - WebSockets - Connecting: api-reference/dex-api/ws-connection.md
    - WebSockets - Streams: api-reference/dex-api/ws-streams.md
    - Node RPC: api-reference/node-rpc.md
    - API Server: api-reference/api-server.md
    - Light Client: light-client.md
    - SDK: api-reference/sdk.md
    - Commands: api-reference/cli.md
    - Transactions: encoding.md
    - WalletConnect: walletconnect.md
    - RPC Swagger: rpc-swagger/index.html
    - Accelerated Node API Swagger: api-swagger/index.html
    - Changelog: changelog.md
  - Guides:
    -  Concepts:
       - Blockchain Concepts:
          - Architecture: guides/concepts/architecture.md
          - Accounts: guides/concepts/accounts.md
          - Assets: guides/concepts/assets.md
          - Transaction: guides/concepts/transaction.md
          - Genesis File: guides/concepts/genesis.md
          - Signature: guides/concepts/signature.md
          - Encoding:
            - Encoding: guides/concepts/encoding/encoding.md
            - Amino Encoding: guides/concepts/encoding/amino-example.md
       - Binance Chain and DEX:
         - Fees: guides/concepts/fees.md
         - Binance Chain Governance: governance.md
         - Match Engine: trading-spec.md
         - Threshold Signature Scheme: guides/concepts/threshold-signature-scheme.md
         - Atomic Swap: atomic-swap.md
         - WalletConnect: guides/concepts/walletconnect.md
    - Get Started:
      - Introduction: guides/intro.md
      - Create Address: guides/create-address.md
      - Binance DEX Ttrading: guides/trading-interface.md
      - Binance Chain Testnet: guides/testnet.md
  - FAQ:
      - FAQ: faq/faq.md
  - Wallets:
    - Binance Chain Walletsupport: wallets/wallets.md
    - Wallet Tutorial:
      - Trust Wallet User Guide: wallets/tutorial/how-to-create-a-wallet-on-trustwallet.md
      - Ledger Wallet Guide: wallets/tutorial/ledger-nano-s-usage-guide.md
      - Trezor Wallet Guide: wallets/tutorial/trezor-model-t-user-guide.md
    - WalletConnectSupport: wallets/walletconnect-support.md
  - Exchange Integration: exchange-integration.md
  - List Instructions: list_instruction.md
  - Wallets: wallets.md
  - More Help: resources.md
  - Binance DEX TestNet: https://testnet.binance.org
  - Chain Explorer TestNet: https://testnet-explorer.binance.org
  - Get Testnet Funds: https://www.binance.vision/tutorials/binance-dex-funding-your-testnet-account

markdown_extensions:
    - admonition
    - pymdownx.arithmatex
    - pymdownx.superfences
    - codehilite



plugins:
  - search:
      prebuild_index: true

repo_name: 'binance-chain/docs-site'
repo_url: 'https://github.com/binance-chain/docs-site'

extra:
  social:
    - type: 'github'
      link: 'binance-chain/docs-site'
    - type: 'twitter'
      link: 'https://twitter.com/Binance_DEX'
    - type: 'website'
      link: 'https://www.binance.org'