site_name: Binance Chain Docs
site_description: Binance Chain Technology Documentation
site_author: Binance Chain Community

repo_url: https://github.com/binance-chain/
edit_uri: ""
use_directory_urls: false

theme:
  name: 'material'
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: 'yellow'
    accent: 'grey'
  logo:
    icon: 'build'
  feature:
    tabs: true
extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css


nav:
  - Home: index.md
  - API Reference:
    - HTTP API - Paths and Models: api-reference/dex-api/paths.md
    - WebSockets - Connecting: api-reference/dex-api/ws-connection.md
    - WebSockets - Streams: api-reference/dex-api/ws-streams.md
    - Node RPC: api-reference/node-rpc.md
    - API Server: api-reference/api-server.md
    - Light Client: light-client.md
    - SDK: api-reference/sdk.md
    - Commands: api-reference/cli.md
    - Transactions: encoding.md
    - WalletConnect: walletconnect.md
    - Changelog: changelog.md
  - Guides:
    -  Concepts:
       - Architecture: guides/concepts/architecture.md
       - Accounts: guides/concepts/accounts.md
       - Address: guides/concepts/address.md
  - FAQ:
      - FAQ: faq/faq.md
  - Exchange Integration: exchange-integration.md
  - RPC Swagger: rpc-swagger/index.html
  - API Swagger: api-swagger/index.html
  - List Instructions: list_instruction.md
  - Wallets: wallets.md
  - Tutorials: tutorials.md
  - More Help: resources.md
  - Binance DEX TestNet: https://testnet.binance.org
  - Chain Explorer TestNet: https://testnet-explorer.binance.org
  - Get Testnet Funds: https://www.binance.vision/tutorials/binance-dex-funding-your-testnet-account

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list
    - codehilite


plugins:
  - search:
      prebuild_index: true

repo_name: 'binance-chain/docs-site'
repo_url: 'https://github.com/binance-chain/docs-site'

extra:
  social:
    - type: 'github'
      link: 'binance-chain/docs-site'
    - type: 'twitter'
      link: 'https://twitter.com/Binance_DEX'
    - type: 'website'
      link: 'https://www.binance.org'